version: '3.8'
services:
  test-app-java-spring:
    container_name: test-app-java-spring
    build:
      context: test-app-java-spring
      dockerfile: Dockerfile
    image: test-app-java-spring:latest
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=springtest17052023
      - MYSQL_ROOT_PASSWORD=Password123#
    ports:
      - "33060:33060"
      - "3306:3306"